package fsm

const (
	StateInit           = "init"
	StateWelcome        = "welcome"
	StateAwaitingAnswer = "awaiting_answer"
	StateWaitingReview  = "waiting_review"
	StateCompleted      = "completed"

	StateAdminMenu          = "admin_menu"
	StateAdminAddStep       = "admin_add_step"
	StateAdminEditStep      = "admin_edit_step"
	StateAdminManageAnswers = "admin_manage_answers"
	StateAdminEditSettings  = "admin_edit_settings"

	StateAdminAddStepText         = "admin_add_step_text"
	StateAdminAddStepType         = "admin_add_step_type"
	StateAdminAddStepImages       = "admin_add_step_images"
	StateAdminAddCorrectImage     = "admin_add_correct_image"
	StateAdminReplaceCorrectImage = "admin_replace_correct_image"
	StateAdminDeleteCorrectImage  = "admin_delete_correct_image"
	StateAdminAddStepAnswers      = "admin_add_step_answers"
	StateAdminEditStepText        = "admin_edit_step_text"
	StateAdminEditStepImages      = "admin_edit_step_images"
	StateAdminManageImages        = "admin_manage_images"
	StateAdminAddImage            = "admin_add_image"
	StateAdminReplaceImage        = "admin_replace_image"
	StateAdminDeleteImage         = "admin_delete_image"
	StateAdminAddAnswer           = "admin_add_answer"
	StateAdminDeleteAnswer        = "admin_delete_answer"
	StateAdminEditSettingValue    = "admin_edit_setting_value"
	StateAdminUserList            = "admin_user_list"
	StateAdminUserDetails         = "admin_user_details"
	StateAdminAddHintText         = "admin_add_hint_text"
	StateAdminAddHintImage        = "admin_add_hint_image"
	StateAdminEditHintText        = "admin_edit_hint_text"
	StateAdminEditHintImage       = "admin_edit_hint_image"
	StateAdminBackup              = "admin_backup"
)
